- .github/workflows/tests.yml
- CMakeLists.txt
- README.md
- eos/eos.hpp
- eos/eos_stellar_collapse.cpp
- test/CMakeLists.txt
- test/profile_stellar_collapse.cpp
- test/test_eos_spiner.cpp
- utils/fast-math/logs.hpp
- utils/scripts/make_tabulated_gamma.py
- utils/scripts/units.py
- utils/stellarcollapse2spiner/CMakeLists.txt
- utils/stellarcollapse2spiner/main.cpp
Adds a tool to profile the stellar tables. Also adds a few bug fixes to the build system and fixes things that got broken in the move to github.
> Profile Stellar Collapse

- README.md
Update the readme to reflect the name change mix->closure.  This was one outstanding thing
> Change mix to closure in README

- test/eos_unit_tests.cpp
small change to fix error in build tests
https://github.com/lanl/singularity-eos/issues/11
> Small change in eos_unit_test

- eos/eos_stellar_collapse.cpp
- test/profile_stellar_collapse.cpp
Instrument root finding on the host.
> add histogram for profile stellar collapse

- spack-repo/packages/singularity-eos_deps/package.py
Default for `kokkos` set to off
> Spec changed default of kokkos to off

- .github/workflows/docs.yml
This should get the docs to rebuild when we create a release.
> also rebuild docs on release

- .gitlab-ci.yml
- doc/sphinx/src/sphinx-doc.rst
- spack-repo/packages/py-sphinx-multiversion/package.py
Gitlab Pages was broken due to missing dependency, namely the sphinx-multiversion.
Pulling in the package through spack to resolve that issue.
> Add sphinx multiversion as dependency in the spack stack for gitlab pages

- .gitlab-ci.yml
Only need to run `pages_check` on MR since it would be redundant with the `pages` after merging into `main`
> only need to run pages_check on MR

- .gitlab-ci.yml
- .gitlab-ci/config/spack/modules.yaml
- .gitlab-ci/config/spack/upstreams.yaml
Switch to the spack in the xcap oss project space for gitlab ci
> Use project spack instead of temporary spack in local space

- spack-repo/packages/singularity-eos/package.py
This PR will replace the `singularity-eos-deps` spack package with a full `singularity-eos` spack package in `spack-repo`, allowing for both installing dependencies and the library.
> Spack package

- spack-repo/packages/singularity-eos/package.py
Add homepage string to spackage, fixes #57
> added homepage string to package.py

- spack-repo/packages/singularity-eos/package.py
> fixed a type in package.py

- doc/sphinx/src/building.rst
Document how to build `singularity-eos` in all its complicated glory.
> add build doc

- singularity-eos/eos/eos_stellar_collapse.cpp
2 line fix for stellar collapse table.
> bug fix for stellar collapse table

- README.md
- cmake/Format.cmake
As discussed [here](https://github.com/lanl/spiner/pull/21) multiple submodules in an in-tree build may define their own format targets. To avoid this name collision, I am namespacing the format target.
> namespace the format target

- doc/sphinx/src/building.rst
- spack-repo/packages/singularity-eos/package.py
Changes:
- `mpi` variant propagated to dependencies correctly
- re-implementation of cmake configuration file generation.
- documentation stubs
Fixing various issues with spack installations that have arisen. Will try and address open issues here.
> Spack updates

- test/eos_unit_tests.cpp
This uses the host eos to evaluate a comparison value on the host which was breaking for GPU builds. 
- [n/a ] Adds a test for any bugs fixed. Adds tests for new features. -- fixes a test
- [ n/a] Document any new features, update documentation for changes made.
> Use host eos to evaluate value on host.

- .github/workflows/formatting.yml
- README.md
- utils/scripts/format.sh
Adds a format script for those who don't want to use cmake. Also fixes the github workflow to die if formatting check fails.
> format script

- singularity-eos/eos/eos.hpp
Introduced by me in #109. Reported by @mauneyc-LANL . Resovles #112 .
> Remove extraneous `SG_USING`. Resolves #112

- .gitlab-ci.yml
Fix x86 volta job and take out the temporary one
> Fix x86 volta gitlab CI job

- singularity-eos/eos/eos.hpp
- test/test_eos_gruneisen.cpp
> Add warning when provided rho_max is greater than the computed rho_max

- .gitlab-ci.yml
> reorg spack env setup

- CHANGELOG.md
- doc/sphinx/src/building.rst
I think it would be good to document build commands and sequences we find useful for ourselves or others. I'll start us off by adding how to build the python wrappers in a virtual environment.
> add python build example

- CHANGELOG.md
- CMakeLists.txt
> Release candidate/1.6.2

- .gitlab-ci.yml
Added temp spack version and dir variables and logic to handle them when defined.
This is so the update to spack v0.18.1 does not break the CI, but when the issues are resolves, still easy to just use the project default spack version and dir.
> added temp spack version/path and logic to handle them

- .github/workflows/docs.yml
- .github/workflows/formatting.yml
- .github/workflows/tests.yml
- .github/workflows/tests_minimal.yml
- CHANGELOG.md
- singularity-eos/base/constants.hpp
- singularity-eos/eos/eos_eospac.hpp
- singularity-eos/eos/eos_gruneisen.hpp
- singularity-eos/eos/eos_spiner.hpp
- singularity-eos/eos/eos_stellar_collapse.hpp
- singularity-eos/eos/modifiers/relativistic_eos.hpp
In PR #202 @aematts noticed that `robust_utils.hpp` defines `EPS` and `constants` defines `EPS` and these two definitions can conflict. Here I remove the version in `constants.hpp`. I also noticed that tests are failing as of yesterday, I think due to some change in the docker instance used for github actions. This PR includes an attempted fix for that as well.
> fix epsilon

- .github/workflows/docs.yml
- doc/sphinx/src/building.rst
> Fix Documentation Warnings

- .gitlab-ci.yml
- removes the `spack dev-build` for MRs, will only run on `main` branch
- removes internet dependence for creating spack upstream
- changes how spack env is built
- adds JUnit XML output as artifact and adds `Tests` tab in GitLab jobs
- adds collapsed sections for various build phases
> Refactor GitLab CI

- spack-repo/packages/singularity-eos/package.py
Some minor changes to the spackage to keep it similar to Spack upstream
> Sync spackage with upstream

- .gitlab-ci.yml
Darwin has moved nodes from the power9 partition and it only has 2 nodes left, we need to move to the new one, so the CI jobs won't hang all the time.
Also, carrying over the cuda update Richard proposed in spiner MR (https://github.com/lanl/spiner/pull/63)
> update partition name and cuda version

- .gitlab-ci.yml
Fix the cuda module version that's being loaded
> fix module load cuda version

- CMakeLists.txt
This is a replacement for #230 .
The export/install stage will generate the file `singularity-eosConfig.cmake`, which is used by the `find_package()` command downstream. This file checks for the required dependencies, defines targets and some variables.
```cmake
if(NOT spiner_FOUND OR NOT TARGET spiner::spiner)
find_package(spiner  REQUIRED)
endif()
if(NOT HDF5_FOUND OR NOT TARGET hdf5::hdf5 OR NOT TARGET hdf5::hdf5_hl)
find_package(HDF5 COMPONENTS C;HL REQUIRED)
endif()
if(NOT MPI_FOUND OR NOT TARGET MPI::MPI_CXX)
find_package(MPI COMPONENTS CXX REQUIRED)
endif()
```
There was a typo in the variable used to add `EOSPAC` to the set of required packages, and a variable for checking on the correct target guard. With this fix, we have the correct propagation:
```cmake
if(NOT spiner_FOUND OR …
```
> Fix for EOSPAC export/install scripts

- doc/sphinx/src/contributing.rst
Simple MR to add a bit of detail to the process for adding a test when you create a new EOS.
@gopsub let me know if this is sufficient
- N/A Make sure the copyright notice on any files you modified is up to date.
- N/A After creating a pull request, note it in the CHANGELOG.md file
> Add detail to procedure for creating tests in the contributing section

- .github/workflows/deps.yml
> Fix GitHub bot workflow

- CHANGELOG.md
- singularity-eos/eos/eos_eospac.hpp
> Add missing eosSafeDestroy call

- CHANGELOG.md
- test/test_eos_sap_polynomial.cpp
What it says on the can. Missing deep copy in the tests code. Only appears on GPU builds.
> fix eos tests on GPUs for SAP EOS. missing deep copy

- singularity-eos/eos/singularity_eos.cpp
- singularity-eos/eos/singularity_eos.hpp
Adds a missing C++ function to initialize the Fortran interface for the SAP_Polynomial EOS.
- N/A After creating a pull request, note it in the CHANGELOG.md file
> Fix SAP_Polynomial Fortran interface

- .gitlab-ci.yml
> CI: Update SITE_ID_TOKEN to asc-git.lanl.gov

- test/test_eos_helmholtz.cpp
Fixes an issue with the Helmholtz EOS test where (on some systems, it does not seem to appear in the CI/CD) the tests fail because ``rho_in`` changes its value. Presumable due to the input ``lambda`` only having two elements while the three elements are expected. This (probably?) causes the modification of ``rho_in[0]``. Providing a three element ``lambda`` fixes this issue.
<details>
<summary>Example output (note change in rho before and after first EOS call) </summary>
```
[Before] rho = 0.001, temp = 10000, lambda = 4, 2
[After] rho = 4, temp = 10000, lambda = 4, 2
rho = 4, temp = 10000, lambda = 4, 2
ein = 9.42248e+11, press = 3.27489e+13
[Before] rho = 4, temp = 1e+06, lambda = 4, 2
[After] rho = 6, temp = 1e+06, lambda = 4, 2
rho = 6, temp = 1e+06, lambda = 4, 2
ein = 9.62892e+13, …
```
> Fix issue with Helmholtz EOS test

- singularity-eos/CMakeLists.txt
Fixes install bug noted in #312
> Add eos_sap_polynomial to list of headers for install

- CHANGELOG.md
- CMakeLists.txt
> release candidate v1.8.0-rc

- spack-repo/packages/singularity-eos/package.py
> update spackage for release-v1.8.0

- doc/sphinx/src/models.rst
> Fixed typo in documentation

- CHANGELOG.md
- CMakeLists.txt
- utils/scripts/make_tabulated_ideal_sc.py
PR #338 pulls in additional data from the files, which wasn't included in the synthetic gold files. This PR adds the relevant data to the gold file generator script and points to the new goldfile.
> update gold files

- .gitlab-ci.yml
XCAP deployment changes that require update to our CI.
> More CI changes

- joss-paper/paper.md
> add ktsai ORCID to JOSS paper

- .gitlab-ci.yml
Spack upstreams are now split up by cluster.
> ci: add TESTING_CLUSTER to PROJECT_SPACK_ROOT

- joss-paper/paper.md
> Remove extraneous dash form orcid in paper

- joss-paper/paper.md
> Fix author typos

- joss-paper/paper.md
> More Orcids

- singularity-eos/eos/eos_carnahan_starling.hpp
The original MR got merged before everything was fixed. This NEEDS to pass on gitlab before being merged
> Carnahan Starling fixes

- spack-repo/packages/singularity-eos/package.py
Fixes the re-git CI on Roci by requiring certain binutils versions
> spack: avoid broken binutils

- doc/sphinx/src/using-eos.rst
> Fix typo in documentation regarding bulk modulus

- doc/sphinx/src/building.rst
- doc/sphinx/src/contributing.rst
- doc/sphinx/src/getting-started.rst
- doc/sphinx/src/using-closures.rst
- joss-paper/paper.md
> Typos found during JOSS review

- .github/PULL_REQUEST_TEMPLATE.md
- spack-repo/packages/singularity-eos/package.py
We have updated some of our dependencies since the last version. This change simply updates the `package.py` to reflect that the new version will depend on these new packages.
Specifically, the two main updates are
- ports-of-call to 1.6.0
- Catch2 to version 3
- N/A After creating a pull request, note it in the CHANGELOG.md file.
> Update spackage in preparation for release

- CHANGELOG.md
- CMakeLists.txt
It's finally time @mauneyc-LANL .
> update C++ standard to 17

- joss-paper/paper.md
> Add references heading at bottom of paper

- CHANGELOG.md
- CMakeLists.txt
> prepare for release 1.9.1

- .gitlab/build_and_test.sh
- spack-repo/packages/ports-of-call/package.py
- spack-repo/packages/singularity-eos/package.py
- spack-repo/packages/spiner/package.py
- spack-repo/repo.yaml
- migrate changes from spiner/ports-of-call
- add new versions (replaces #431)
- update `build_and_test.sh` with various improvements
> CI Updates

- singularity-eos/eos/eos_electrons.hpp
- singularity-eos/eos/modifiers/zsplit_eos.hpp
> hotfix to build in riot

- CHANGELOG.md
- doc/sphinx/src/models.rst
- sesame2spiner/examples/unit_tests/steel.dat
- sesame2spiner/generate_files.cpp
- sesame2spiner/generate_files.hpp
- sesame2spiner/io_eospac.cpp
- sesame2spiner/io_eospac.hpp
- singularity-eos/base/constants.hpp
- singularity-eos/base/sp5/singularity_eos_sp5.hpp
- singularity-eos/closure/mixed_cell_models.hpp
- singularity-eos/eos/eos_electrons.hpp
- singularity-eos/eos/eos_eospac.hpp
- singularity-eos/eos/eos_spiner.hpp
- singularity-eos/eos/get_sg_eos_rho_p.cpp
- singularity-eos/eos/modifiers/zsplit_eos.hpp
- singularity-eos/eos/singularity_eos.cpp
- singularity-eos/eos/singularity_eos_init_utils.hpp
- test/profile_eospac.cpp
- test/test_eos_tabulated.cpp
- test/test_pte.cpp
- test/test_pte_ideal.cpp
> merge main

- .gitlab-ci.yml
- CMakeLists.txt
- python/module.hpp
- adds re-git builds with Clang 19 on CPU
- fixes a preprocessor issue in the Python bindings
> Add Clang builds for CPU

- CHANGELOG.md
- spack-repo/packages/singularity-eos/package.py
When the last release was made, it looks like the spack dependencies weren't updated for the new spiner piecewise grids. This MR adjusts the spack logic so that newer versions correctly require newer spiner versions.
> Update package.py for spiner feature changes

- CHANGELOG.md
- CMakeLists.txt
> release candidate 1.9.2

- spack-repo/packages/singularity-eos/package.py
> [trivial] update spackage for release 1.9.2

- CHANGELOG.md
- doc/sphinx/index.rst
- doc/sphinx/src/fortran.rst
Adds rudimentary Fortran interface documentation.
This PR adds documentation for all available Fortran functions, and tries to explain the arguments of each function. I've also added two examples at the bottom that use some of the functions.
The function signatures might be a bit verbose, let me know what you think. I can make it more concise.
Addresses #490
> Add Basic Fortran Interface Documentation

- CHANGELOG.md
- singularity-eos/eos/eos_spiner.hpp
- test/test_eos_tabulated.cpp
> Added the coldcurve to spinerEOSDependsRhoSIe with test

- spack-repo/v1/packages/singularity-eos/package.py
- spack-repo/v2/spack_repo/singularity_eos/packages/singularity_eos/package.py
> update versions available in spackage

- CHANGELOG.md
- doc/sphinx/src/contributing.rst
- singularity-eos/closure/mixed_cell_models.hpp
This addresses @dholladay00 's concern about MR #548 . After some discussion offline, I believe this comment covers concerns.
> document the intent of the virtual keyword in solvers

- CHANGELOG.md
- spack-repo/v1/packages/singularity-eos/package.py
- spack-repo/v2/spack_repo/singularity_eos/packages/singularity_eos/package.py
We really only need to require kokkos-kernels when we have the closure models enabled as well. Otherwise they aren't needed.
This is also true for Eigen
> Correct logic for kokkos-kernels in package.py
