CMakeLists.txt
README.md
eos/eos.hpp
eos/eos_stellar_collapse.cpp
eos/eos_variant.hpp
test/eos_unit_tests.cpp
utils/cuda_compatibility.patch
utils/stellarcollapse2spiner/main.cpp

This PR contains some minor fixes for quality of life downstream. In particular:
- Warnings are eliminated for cuda builds. Most significantly, I remove the `__host__ __device` tags from defaulted functions, which removes a bunch of warnings. However, I also hide some unused variables, etc.
- I fix some includes in `stellarcollapse2spiner` and disable building this tool by default.

Minor tweaks and fixes for quality of life downstream

---

sesame2spiner/io_eospac.cpp

eos_SetOption can only set a single option in a call. 
EOS_INSERT_DATA is now set to 4 as was the intention in the original code.

Fix usage of eos_setOption

---

.gitlab-ci.yml
sesame2spiner/examples/duplicate-test/air.dat
sesame2spiner/examples/duplicate-test/air2.dat
sesame2spiner/examples/duplicate-test/steel.dat
sesame2spiner/examples/duplicate-test/titanium.dat
sesame2spiner/generate_files.cpp

In issue #47 @dholladay00 discovered that if two materials in a sesame2spiner file have the same "name" metadata, HDF5 throws an error. This PR adds guard rails so this can't happen, and also adds guard rails against a similar error when duplicate matids are requested.
Strategy uses a simple `std::unordered_list` to see what has been used already.
Resolves #47

fix issues with duplicate names

---

sesame2spiner/generate_files.cpp

As discussed on mattermost, implements a fix for the discovered issue where for some inputs within machine precision of the boundary of a table, eospac produces incorrect output.
While we haven't yet figured out what is going on (I'm working on a self-contained reproducer), I argue that this change is harmless and avoids the issue, so we should move forward with it in `sesame2spiner`.

implement workaround for table edge issue

---

example/CMakeLists.txt
example/get_sesame_state.cpp
sesame2spiner/generate_files.cpp
sesame2spiner/io_eospac.hpp
singularity-eos/eos/eos_spiner.cpp
test/eos_unit_tests.cpp

@annapiegra noticed that `SpinerEOSDependsRhoT` was producing an artifact near the top of the table, right around when the code switches to extrapolation. This was caused by two issues:
1. `sesame2spiner` offsets the grid log grid bounds slightly based on STP. The intent is that this regridding sets up exactly one grid point at standard density and one at standard temperature. To do so, I change the grid spacing and bounds slightly from what's specified in the file. This machinery was accidentally removing too many points from the top of the grid. It now removes *exactly* one point, meaning the upper bound of the table is closer to what's expected.
2. There was a bug in the extrapolation routines of `SpinerEOSDependsRhoT` where the Gruneisen parameter used for the ideal gas extrapolation …

Fix the issue in extrapolation

---

singularity-eos/eos/eos.hpp

Fix bug in the Gruneisen parameter for the Gruneisen EOS
As implemented, the energy derivative of the pressure for this EOS would take the following form:
However, this form violates a key property of the Gruneisen EOS where the energy derivative should be constant when the parameter b = 0. Changing the first rho to rho_0 fixes this problem in the above equation which results in a Gruneisen parameter given by
which is consistent with the energy derivative being constant when b=0. This is also consistent with the corrected EOS in other hydocodes.
Note that this is part of updating documentation so I'll update the documentation in a separate MR.
@chadmeyer can you review this

Correct Gruneisen parameter formula

---

singularity-eos/eos/eos_jwl.cpp

It appears that the reference energy and pressure for the JWL EOS were swapped as a typo.
The reference curve for the JWL EOS is an isentrope and a quick sanity check is that the pressure should be exactly equal to the volume derivative of the energy along the isentrope. This fix makes that true.
My fix is also consistent with xRAGE.

Fix for JWL EOS

---

spack-repo/packages/singularity-eos/package.py

`kokkos-kernels` did not provide a `shared` variant to their package until (I believe) spack v0.16.3. I've updated the `package.py` to check for this and not use the variant if the spack version is lower.

Update spackage to use older versions of spack

---

spack-repo/packages/singularity-eos/package.py

Changes `hdf5` dependency variants from `hdf5+cxx+hl` to `hdf5+hl`
@annapiegra reported conflicts with using the `+cxx` variant. Removed this from `package.py`

remove explicit C++ variant of hdf5

---

singularity-eos/closure/mixed_cell_models.hpp

This PR adds a new call that solves for PTE assuming an ideal gas form, which is simple and analytic, and can replace the initial guesses for the full PTE solve based on some measure of whether the new guess is better.  The metric that decides if the new guess is superior can probably use work.  When the mixture is of ideal gases, this new guess is the exact result, and some reordering of the subsequent solve means that in that case no Newton iterations are performed.  This leads to a pretty substantial performance win for problems with ideal gases or when the ideal gas assumption isn't unreasonable in the relevant part of the EOS.
Curious if people have thoughts.  @chadmeyer @jhp-lanl @jonahm-LANL

Try the ideal gas PTE solution as initial guesses for PTE solver

---

spack-repo/packages/singularity-eos/package.py

The fix for older spack versions would append `kokkos-kernels` to specs that did not specify it. Here, a `when` is added to ensure it is only included when requested in the spec.

Fix kokkos-kernels depends condition

---

.gitlab-ci.yml
singularity-eos/eos/CMakeLists.txt
singularity-eos/eos/eos_base.hpp

It turns out the vector interface on GPUs was only working on Power9s thanks to undefined behavior. This PR fixes it. The issue was that the `*this` pointer was being captured in the lambdas in the portable for in the base class.
To rectify, I dereference the `*this` pointer to make a copy of the derived class to pass into the `portableFor`.
To correctly test this, we need a CI build matrix for x86-volta nodes. I have added one, but some extra eyes from, e.g., @ktsai7, @junghans , or @dholladay00  would be welcome.

Fix vector interface on GPUs

---

singularity-eos/eos/eos.hpp

Fix using statements for EOSPAC to properly use the EOSPAC class as the template parameter instead of SpinerEOSDependsRhoSie.
This bug was introduced in https://github.com/lanl/singularity-eos/pull/109

Fix bug in EOSPAC using statements

---

CMakeLists.txt
doc/sphinx/src/contributing.rst
doc/sphinx/src/getting-started.rst
doc/sphinx/src/models.rst
sesame2spiner/io_eospac.hpp
singularity-eos/eos/eos.hpp
test/eos_unit_tests.cpp
utils/fast-math/logs.hpp

This PR emerged from a discussion with @jdolence . @jdolence noticed that when using fast logs, the following was not true:
```C++
std::abs(pow(10., singularity::Math::Log10(x)) - x) < EPSILON
```
for some `EPSILON`. This was because we do fast logs, but we don't have a fast exponential to undo it in the exact same, approximate way. This may have implications for the accuracy of `P(rho,sie)` calls for `SpinerEOSDependsRhoT` though it should be a small effect.
To resolve this, @jdolence and I revisited the idea of log-linear interpolation. The reason we use log space is because logs are easy, and the grid spacing for a logarithmically spaced grid is roughly proportional to the size of the independent variable. *It doesn't actually matter that it be a logarithm exactly.* What matters is …

Fast, approximate and invertible logs

---

utils/root-finding-1d/root_finding.hpp

Change the `#define`s in `utils/root-finding-1d/root_finding.hpp` to be prefixed with `SINGULARITY_`, to avoid possible collisions with names/symbols downstream
There is also a presently in the code I'm not sure about, see Summary
As I understand it, this root-find shares a common origin in GSL; it is no only possible that other codes do so, but I in fact hit an issue when integrating `singularity-eos` into a code that does something similar. The results were lots of weird errors that ended up being these preprocessor directives over-writing variables names.
To prevent this in future, this PR changes the strings of these `#define`s to try and avoid possible future collisions.
There is also a possible unnecessary `#define` (originally `utils/root-finding-1d/root_finding.hpp:34`) :
```c++ …
```

changed defines to avoid collisions downstream

---

singularity-eos/eos/modifiers/shifted_eos.hpp

Small update to remove compiler warnings about `extra tokens at end of #endif directive`
Both GNU/Clang are unhappy about stuff after `#endif`s. There was some of this in `singularity-eos/eos/modifiers/shifted_eos.hpp`. I simply commented out the string.

Removing "extra tokens" warning

---

spack-repo/packages/singularity-eos/package.py

Make eospac a variant in singularity-eos spackage. (Eospac was already listed as a dependency)
Spack looks for eospac in the spec to determine if eospac should be pulled in:           self.define("SINGULARITY_USE_EOSPAC", "^eospac" in self.spec)
Spack env builds on CTS1_intel.

Add eospac variant to spackage

---

singularity-eos/closure/mixed_cell_models.hpp
singularity-eos/eos/eos_spiner.cpp

This is a very small update that iteratively searches for an initial temperature guess such that the initial material densities are always above the density at pressure minimum at that temperature.
Also includes a tiny bug fix in the calculation of cold curves in SpinerDependsRhoT.

More robust initial guess for temperature in PTE

---

singularity-eos/closure/mixed_cell_models.hpp

This changes the preprocessor directive when compiling with `kokkos` + `Eigen` to a `#warning`, so that the code will not halt compilation in this case.
This is a temporary fix for #125  . Ideally this (and other) directives will be superseded by the build configuration stage.

error to warning when using Kokkos and Eigen

---

singularity-eos/closure/mixed_cell_models.hpp

Decorating default constructors/destructors produces a warning when building for CUDA.  This just removes a PORTABLE_INLINE_FUNCTION on the default constructor for the `CacheAccessor` class used internally for the PTE solve.

remove PORTABLE_INLINE_FUNCTION on default constructor of CacheAccessor

---

.github/workflows/docs.yml

When people on forks submit a PR, the docs test fails because the fork doesn't have permission to deploy the docs to github pages. This PR hopefully resolves the issue by disabling the deployment on PRs from forks. (Tested in Spiner.)

fix docs deploy on forks

---

test/test_eos_gruneisen.cpp

Changes the input parameters for one of the Gruneisen tests so that it uses an exact root rather than an irrational root whose solution is itself subject to root finding tolerances. The combination of these tolerances and those of our own root finder seems to be on the very edge of the test tolerance, causing it to fail on Power9 without debug flags.

Change Gruneisen test to use a rational root instead of an irrational root

---

singularity-eos/eos/eos_gruneisen.cpp

Changes the root finding tolerances used in the Gruneisen EOS to be related to machine epsilon. The function where this is used computes the maximum allowable density for the EOS given a fit to the Hugoniot.
I'm using a smaller tolerance for y than x in this case because it is possible that a local extremum will be the root (or will be very close to the root), causing the dy/dx derivative at the root to be very small. Previously the tolerances had been equal, in which case the small derivative would cause a small y tolerance to become a much larger (perhaps unacceptably so) tolerance in x.

Make Gruneisen EOS root finding tolerance a function of machine epsilon

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
doc/sphinx/index.rst
doc/sphinx/src/contributing.rst
sesame2spiner/README.md

It's getting a little tough to keep track of all changes that go into the code. This adds a changelog, based on the way we do things in Parthenon. I also cleaned up the docs and READMEs a little while I was at it.

changelog and cleanup

---

.gitlab-ci.yml
CMakeLists.txt
spack-repo/packages/catch2/package.py
spack-repo/packages/ports-of-call/package.py
spack-repo/packages/singularity-eos/package.py
spack-repo/packages/spiner/package.py

This PR and its Gitlab counterpart are used to prepare `singularity-eos` and its spackage to be upstreamed to `spack/spack`.

 Update spackage to use spack dependencies instead of submodules

---

CHANGELOG.md
singularity-eos/eos/eos_davis.cpp
singularity-eos/eos/eos_gruneisen.cpp
singularity-eos/eos/eos_jwl.cpp

Replaces the original hand-written solvers using a naive secant method (with a bug!) with the now present `regula_falsi` solver. 
The buggy versions were in the Gruneisen EOS and the two Davis EOSs, and there was a slightly less buggy version (which had the missing abs) in JWL, but it makes sense for these to be put together for consistency.

Replace secant method with regula_falsi

---

spack-repo/packages/singularity-eos/package.py

Makes pybind11 a Spack dependency when building the Python bindings.

Add py-pybind11 as Spack dependency

---

CHANGELOG.md
doc/sphinx/src/using-closures.rst
singularity-eos/closure/mixed_cell_models.hpp
test/test_pte.cpp

This PR introduces a function that solves $u_0 = \sum_m \rho_m \alpha_m \epsilon_m(\rho_m, T)$ for the temperature $T$, for fixed input $u_0$ (total material energy density, i.e. $erg/cm^{3}$), $\alpha_m$ (material volume fractions), and $\rho_m$ (material physical densities).  The intent of the function is to be used to provide an initial guess for the PTE solver, so the hard coded tolerance of the solver is quite loose.  Bisection is used because it's better behaved for EOSs that have only a weak dependence of $\epsilon$ on $T$ at cold temperatures.
To go along with this, the PTE solvers have been augmented to allow an initial temperature guess to be (optionally) provided.  If a guess is not provided, or the guess is zero, the solver tries to guess a temperature as before.

Provide a function to give initial temperature guesses for PTE

---

CHANGELOG.md
CMakeLists.txt

I recently tried to compile `singularity-eos` against a Kokkos release candidate, rather than a firm version, and I discovered that the version is not appropriately populated in `cmake`. This adds guard rails for this use-case, where `cmake` warns the user that it could not correctly infer `Kokkos`'s version number, but then chugs along anyway.
@mauneyc-LANL please take a look at this. It's somewhat blocking downstream.

let CMake fail to infer version of Kokkos

---

spack-repo/packages/py-pybind11/package.py

Since our GitLab CI is still stuck on v0.16, add the newer py-pybind11 spackage to allow testing.

Add newer py-pybind11 spackage for CI

---

.github/workflows/tests_minimal.yml
CHANGELOG.md
CMakeLists.txt
test/test_eos_unit.cpp

I discovered while debugging some issues for @ktsai7 that the tests do not build with `-DSINGULARITY_BUILD_CLOSURE=OFF` because the closure code is used in `singularity_eos.cpp`, which is called in the tests.
Long term, @dholladay00 I think decoupling closure code from the C/fortran API is probably a good idea. We can tackle that when the xrage-specific stuff moves out of `singularity-eos`. Short term, I have simply fixed the issue by adding appropriate include guards.
I also add a test in github to check that a minimal build configuration can still construct unit tests.

fix fact tests dont build without closure

---

CHANGELOG.md
CMakeLists.txt
cmake/FindHDF5.cmake
cmake/install.cmake
spack-repo/packages/singularity-eos/package.py
test/CMakeLists.txt

Before, we used `cmake` variables that held the `hdf5` configuration data. This PR updates to use `hdf5` interface targets, `HDF5::HDF5; HDF5::hdf5_hl`.
This addresses some CI issues, and makes using HDF5 cleaner.

Use HDF5 targets

---

python/CMakeLists.txt
python/modifier_bilinear_ramp.cpp
python/modifier_relativistic.cpp
python/modifier_scaled.cpp
python/modifier_shifted.cpp
python/modifier_unit_system.cpp
singularity-eos/eos/eos.hpp
singularity-eos/eos/eos_davis.hpp
singularity-eos/eos/eos_eospac.hpp
singularity-eos/eos/eos_gruneisen.hpp
singularity-eos/eos/eos_ideal.hpp
singularity-eos/eos/eos_jwl.hpp
singularity-eos/eos/eos_spiner.hpp
singularity-eos/eos/eos_stellar_collapse.hpp
singularity-eos/eos/modifiers/eos_unitsystem.hpp
singularity-eos/eos/modifiers/ramps_eos.hpp
singularity-eos/eos/modifiers/relativistic_eos.hpp
singularity-eos/eos/modifiers/scaled_eos.hpp
singularity-eos/eos/modifiers/shifted_eos.hpp

This removes a lot of manual template instantiations and instead uses the available typelists to drive their creation.
@Yurlungur  please note that this **removes** a lot of instantiation that don't seem to be covered in the typelists. E.g. `unit_or_rel` does not contain the `Scaled`, `Shifted` and `ScaledShifted` combinations. I'm guessing that typlist is wrong, based on how it was explained to me previously. Another thing that is missing is `UnitSystem` of all `Relativistic` combinations.
Whatever the right set of variants is, the Python mapping is now only dependent on these typelists.

Instantiate Python classes using typelists

---

CHANGELOG.md
cmake/dependency.cmake
cmake/install.cmake

The exported configuration checked for `Eigen3_FOUND` and passed, but the concurrent processing wasn't able to find the interface target `Eigen3::Eigen`. This updates the configuration check to check both.

Checks for found and target in singularity-eosConfig.cmake

---

CHANGELOG.md
CMakeLists.txt
spack-repo/packages/singularity-eos/package.py
test/CMakeLists.txt
test/test_eos_unit.cpp

As requested by @mauneyc-LANL @dholladay00 and motivated by issues @annapiegra is having with oneapi, this PR does the following:
- Stores an hdf5 "gold" file as a release
- Downloads the file in cmake if needed
- Removes `py-h5py` from spack and cmake dependencies.

remove h5py from spack and from tests

---

CHANGELOG.md
README.md
doc/sphinx/src/contributing.rst
singularity-eos/eos/eos_eospac.hpp

#215 apparently was merged prematurely. I fix the remaining issues lingering from that PR. This needs to be run on Darwin before merge.

Clean up the epsilon fix

---

.gitlab-ci.yml
CHANGELOG.md
doc/sphinx/src/sphinx-doc.rst

Github already builds pages and does format checking for us so there's no reason to duplicate this work on re-git. Currently WIP until I test the CI on re-git.

no static on re git

---

.gitlab-ci.yml
.gitmodules
CHANGELOG.md
CMakeLists.txt
doc/sphinx/src/contributing.rst
singularity-eos/base/eos_error.hpp
spack-repo/packages/ports-of-call/package.py
spack-repo/packages/singularity-eos/package.py
spack-repo/packages/spiner/package.py
test/eos_unit_test_helpers.hpp
test/test_eos_unit.cpp

This pulls my error handling machinery through `singularity-eos`, mostly motivated by @aematt's request for testing. I make a few changes of note:
1. I make `ports-of-call` its own submodule. This is unfortunately required for now. Once @mauneyc-LANL 's PR #221 is through, this won't be necessary and the submodule should be removed. Note that I **do not** update `spiner`. I think @mauneyc-LANL 's changes to `spiner` make it incompatible with the submodule path for now. So spiner stays on the old commit until #221 goes through.
2. I create a new macro, `REQUIRE_MAYBE_THROWS` which is to be used in units tests with catch. It either resolves to a `REQUIRE_THROWS` if `PORTABILITY_STRATEGY_NONE` or a no-op. This is what @aematts should use.
3. As a temp hack, I replace `EOS_ERROR` with …

Update ports-of-call and introduce error handling

---

CHANGELOG.md
singularity-eos/eos/eos_stellar_collapse.hpp
test/test_eos_unit.cpp

This PR adds a function `EntropyFromDensityTemperature` to `eos_stellar_collapse.hpp` that interpolates entropy from the tabulated Eos. I added a placeholder test to ensure that the interpolated entropy is comparable to the ideal gas entropy when appropriate.

Add entropy interpolation to stellar collapse

---

CHANGELOG.md
singularity-eos/CMakeLists.txt

Addressing #227 . `singularity-eos/CMakeLists.txt` updated to include all header files in code.
This could be an impetus to automate source file discovery in the build, but my impression is `GLOB` and similar commands are not recommended. This could be an outdated mode of thought, tho.
- N/A  Adds a test for any bugs fixed. Adds tests for new features.
- N/A  Format your changes by using the `make format` command after configuring with `cmake`.

Added untracked headers in cmake

---

CHANGELOG.md
CMakeLists.txt
eospac-wrapper/CMakeLists.txt
sesame2spiner/CMakeLists.txt

Addresses further header includes given in #227 . This time is for `eospac_wrapper.hpp`, which I for some reason thought was a privately used by a binary and not a library archive.
The following is an example of an install:
```bash
$ cmake --install .
-- Install configuration: ""
-- Installing: <install-prefix>/include/eospac-wrapper/eospac_wrapper.hpp
-- Installing: <install-prefix>/lib/libeospac-wrapper.a
-- Installing: <install-prefix>/lib/cmake/singularity-eos/eospac-wrapperTargets.cmake
-- Installing: <install-prefix>/lib/cmake/singularity-eos/eospac-wrapperTargets-noconfig.cmake
-- Installing: <install-prefix>/lib/libsingularity-eos.a
-- Installing: <install-prefix>/lib/cmake/singularity-eos/singularity-eosTargets.cmake
-- Installing: …
```

add eospac-wrapper to install manifest

---

CHANGELOG.md
CMakeLists.txt

Changes to `eospac-wrapper` included some install boilerplate, but these used cmake variables (`CMAKE_INSTALL_LIBDIR`) that were not given a value yet (through `include(GNUInstallDirs)`. 
This adds `include(GNUInstallDirs)` so that these variables are filled.
- N/A Make sure the copyright notice on any files you modified is up to date.

Fix install CMake variables

---

CHANGELOG.md
spack-repo/packages/ports-of-call/package.py

Pretty straight-forward. Just update `ports-of-call` to the latest master.
This is needed to make full use of the portable errors.
- N/A Make sure the copyright notice on any files you modified is up to date.

Update ports-of-call to latest master

---

spack-repo/packages/mpark-variant/icpc.patch
spack-repo/packages/mpark-variant/nvcc.patch
spack-repo/packages/mpark-variant/package.py
spack-repo/packages/mpark-variant/version.patch

Added `mpark-variant` in `spack-repo/packages` as a workaround for a spack internal bug. The `mpark-variant` is just a copy of what's in `Spack v0.19.1`.

add local mpark-variant in spack-repo due to spack bug

---

CHANGELOG.md
doc/sphinx/conf.py

Newer Sphinx and sphinx-rtd-theme do not include jQuery, which is a necessary feature for `sphinx_multiversion` to properly work. This adds the `sphinx_rtd_theme` extension to our doc configuration, which also pulls in `sphinxcontrib-jquery` for us.
See 	https://blog.readthedocs.com/sphinx6-upgrade/

Add explicit dependency to sphinx-rtd-theme (and through it, jQuery)

---

CHANGELOG.md
singularity-eos/base/root-finding-1d/root_finding.hpp
singularity-eos/eos/eos_base.hpp
singularity-eos/eos/eos_davis.hpp
singularity-eos/eos/eos_gruneisen.hpp
singularity-eos/eos/eos_jwl.hpp
singularity-eos/eos/eos_spiner.hpp
singularity-eos/eos/eos_stellar_collapse.hpp
singularity-eos/eos/eos_vinet.hpp
singularity-eos/eos/modifiers/ramps_eos.hpp
singularity-eos/eos/singularity_eos.cpp
test/profile_eos.cpp
test/test_eos_unit.cpp
test/test_eos_vinet.cpp

In a downstream code, @AstroBarker experienced a cuda "unspecified launch failure" for some applications and on some architectures. After some effort, we narrowed it down to the `RootFinding1D::RootCounts` and `RootFinding1D::RootStatus` variables used in the tabulated EOS's. Each EOS had an internal instants of `RootCounts` and `Status` used for diagnostics when the code was run on host in serial. 
Writing to these variables in multiple threads is undefined behavior. However,  I intentionally put the logic in the code anyway. My reasoning was that since they wouldn't be *read* except for diagnostic purposes in serial, this undefined behavior shouldn't cause any problems. This reasoning was apparently incorrect.
I still think these variables are useful, so I don't want to eliminate this …

Limit undefined behaviour and fix some wharnings too

---

CHANGELOG.md
doc/sphinx/src/models.rst
singularity-eos/eos/eos_stellar_collapse.hpp
test/test_eos_unit.cpp

This is a feature needed by NGP code Phoebus, which provides additional astrophysical data tabulated in the stellar collapse table. It should have no effect unless a user specifically pulls a `StellarCollapse` equation of state out of the variant.

add mass fractions to stellarcollapse

---

eospac-wrapper/CMakeLists.txt

`eospac-wrapper` was generating cmake install files seperately from `singularity-eos`
`install(
TARGETS eospac-wrapper EXPORT eospac-wrapperTargets DESTINATION ${CMAKE_INSTALL_LIBDIR}
)`
The `EXPORT eospac-wrapperTargets` specifies a install target file. When `find_package` is used downstream, these files do not get consumed, so cmake reports that there is an dangling target reference to `singularity-eos::eospac-wrapper`.
This PR simplifies the install of `eospac-wrapper`, so that the target is defined in the same file as `singularity-eos`
`install(
TARGETS eospac-wrapper EXPORT singularity-eosTargets DESTINATION ${CMAKE_INSTALL_LIBDIR}
)`

Fix install of eospac-wrapper

---

CHANGELOG.md
doc/sphinx/src/modifiers.rst
doc/sphinx/src/using-eos.rst
singularity-eos/eos/eos_base.hpp
singularity-eos/eos/eos_variant.hpp
singularity-eos/eos/modifiers/eos_unitsystem.hpp
singularity-eos/eos/modifiers/ramps_eos.hpp
singularity-eos/eos/modifiers/relativistic_eos.hpp
singularity-eos/eos/modifiers/scaled_eos.hpp
singularity-eos/eos/modifiers/shifted_eos.hpp
test/test_eos_unit.cpp

Sometimes you may wish to have access to the unmodified model... for example, because you wish to access model-specific features (i.e., the mass fractions in the stellar collapse tables), because you want to drop out of code units and use cgs, or because you wish to swap one modifier for another at runtime.
This PR lets you do those things. I provide three functions, shared across all models, that let you do this:
1. `bool Model::IsModified() const` returns true if the EOS has a modifier applied to it and false otherwise.
2. `auto UnmodifyOnce()` if the EOS is modified, pull off the most recent modifier. Returns either the variant or an appropriate type.
3. `auto GetUnmodifiedObject()` returns the underlying EOS with all modifiers removed. Type again is either the variant or the …

Add the ability to pull an unmodified EOS out of a modified one

---

CHANGELOG.md
singularity-eos/eos/eos_eospac.hpp
test/profile_eospac.cpp

- add check that EOSPAC vector functions are actually faster (profile_eospac)
- prevents slower template to become active in some cases
- adds a warning if slower non scratch version gets called
- Closes https://github.com/lanl/singularity-eos/issues/257

EOSPAC vector performance

---

.github/workflows/deps.yml
.github/workflows/docs.yml
.github/workflows/formatting.yml
.github/workflows/tests.yml
.github/workflows/tests_minimal.yml
doc/sphinx/src/contributing.rst

This adds a manual and scheduled action to check for changes in ports-of-call and spiner spackages and migrate them over to singularity-eos. If a change is detected, it will create a PR authored by a bot.

Add GitHub action to update spackages :robot:

---

CHANGELOG.md
singularity-eos/eos/eos_stellar_collapse.hpp

The Stellar Collapse EOS had a bug where the mass fraction interpolation had two indices swapped. This quick trivial fix remedies the issue.

fix interpolation of mass fractions

---

singularity-eos/eos/eos_base.hpp
singularity-eos/eos/eos_eospac.hpp
singularity-eos/eos/eos_variant.hpp
singularity-eos/eos/modifiers/ramps_eos.hpp
singularity-eos/eos/modifiers/scaled_eos.hpp
singularity-eos/eos/modifiers/shifted_eos.hpp
test/profile_eospac.cpp

Implement modifiers for EOSPAC

---

CHANGELOG.md
spack-repo/packages/singularity-eos/package.py

The bots did their job with the spiner spackage, but because singularity-eos wasn't pinned to a specific spiner release in its own spackage, this broke the CI since spiner is a bit ahead of singularity-eos, at least until @mauneyc-LANL 's PR #246 goes through. This pins singularity to a version of spiner that it works with.
@mauneyc-LANL when you merge PR #246 please make sure to update the spackage here.

revert spiner release in spackage

---

CHANGELOG.md
test/CMakeLists.txt

@jhp-lanl hit an issue where `SINGULARITY_USE_SPINER=OFF` would fail tests that used `spiner`. In a way, the tests worked!
This disables building those tests when `SINGULARITY_USE_SPINER=OFF`

Disable tests that use databox when spiner is off

---

CHANGELOG.md
cmake/singularity-eos/hdf5.cmake
config/singularity-eosConfig.cmake.in

@jhp-lanl found an issue where the exported `singularity-eosConfig.cmake` didn't have guards to check if a target has already been created for dependencies. This would cause an issue with builds where there are common dependencies downstream.
This update includes those guards, and also simplifies the logic.

Fix configuration export

---

CHANGELOG.md
CMakeLists.txt
doc/sphinx/src/building.rst
spack-repo/packages/singularity-eos/package.py

- Add variants for `spiner`
- Refine some depends_on to not grab unnecessary packages
- Make sure CMake args are correct
@dholladay00 @jhp-lanl @jonahm-LANL @rbberger 
Comments/merges/changes. We can discuss more during scheduled meetings.

Updates to package.py

---

CHANGELOG.md
CMakeLists.txt

@jdolence reported an issue downstream when building as submodule !294. The issue was that in submodule mode, `CMAKE_SOURCE_DIR` was pointing to the top-level project's directory and not the `singularity-eos` directory, leading to `list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")` not pointing to anything useful.
Using `PROJECT_SOURCE_DIR` corrects this by using the proper path to the `singularity-eos` source dir.

Change cmake module append to use PROJECT_ insteand of CMAKE_

---

.gitlab-ci.yml

Future proof our re-git CI and some cosmetic changes.

CI updates

---

CHANGELOG.md
doc/sphinx/src/models.rst
python/module.cpp
singularity-eos/base/root-finding-1d/root_finding.hpp
singularity-eos/eos/eos_helmholtz.hpp

Adds a Newton-Raphson root find, specifically for use with the Helmholtz EOS. Although the current ``regula falsi`` produces on average more precise results, it is significantly more expensive. Moreover it is the method used in the originally published paper by Timmes.
<details>
<summary> Plot comparing both root finds </summary>
This benchmark was generated evaluating the EOS at random input values. It is probably not super scientific/ accurate, but should suffice the advantage of the Newton-Raphson root find.
</details>
A few points may (or may not) need to be addressed still:
- The current implementation expects a different function to be passed compared to the other root finds, i.e. it expects a tuple containing the derivative. This works straightforwards with the Helmholtz EOS, but …

Newton-Raphson root find for Helmholtz EOS

---

singularity-eos/eos/eos_eospac.hpp

I am unable to install singularity-eos from spack. This may be a combination of new ports-of-call and overly complicated logic for defining the SG_PIF_NOWARN macro. This simplifies that preprocessor logic that I believe was overly complex. 
If this passes tests, I think we should merge it quickly @Yurlungur @jhp-lanl @rbberger

Simplify logic for defining the nowarn macro.

---

CHANGELOG.md
doc/sphinx/src/using-eos.rst
singularity-eos/eos/eos_base.hpp
singularity-eos/eos/eos_variant.hpp
test/test_eos_unit.cpp

As discussed with @Yurlungur...
This is a tiny PR that adds a fair bit more flexibility to how downstream codes interact with singularity-eos.  The new functionality is a new `Evaluate` template function for both `EosBase` and `Variant` that can take in a downstream-defined functor and evaluate it with the underlying eos object.  This allows one to, for example, express a parallel loop that calls several EOS functions at once in the downstream code, and then have singularity execute that parallel loop with one of the basic EOSs (as opposed to having to visit the variant in every call).
The current vector interface is quite constraining.  For example, if you're running on GPU, it assumes you're calling from the host and that you want to launch a new kernel to make the eos call.  In our …

Add a generic evaluator function

---

CHANGELOG.md
CMakeLists.txt

For #315 , this removes `fmax-errors=3` from the `singularity-eos` build flags. I had put this in when debugging a build, but forgot to remove it later.

Removed max compile errors flag

---

CHANGELOG.md
test/CMakeLists.txt

Move the Vinet test suite into the analytic executable for consistency

Move vinet test from tabulated tests to analytic

---

CHANGELOG.md
singularity-eos/CMakeLists.txt

Adds a missing ``hermite.hpp`` header to the ``EOS_HEADERS`` variable. Required for the Helmholtz EOS in standalone mode.

Fix missing header in CMake install

---

spack-repo/packages/singularity-eos/package.py
spack-repo/repo.yaml

This updates the Singularity-EOS spackage to support plugins. It introduces a new directive `singularity_eos_plugin` which is used to register a plugin with a relative plugin path. While convenient, we still have to see if spack upstream would accept such a spackage change.
The `plugins` variant can then choose one or more of these plugins to be used. Unknown plugin names will result in an error.
`variant` can be used to set the variant header location.

Spackage with Plugin support

---

CHANGELOG.md
cmake/singularity-eos/hdf5.cmake

Recently I had trouble building with HDF5 on Roci and Chicoma when building in-tree. @mauneyc-LANL found the issue, which is, of course, the cray wrappers. This tiny PR short-circuits `singularity-eos` `FindHDF5` machinery when building in-tree on cray. This should have no effect whatsoever on spack builds which, as far as I know, are working on cray systems.

block hdf5 stuff when using cray wrappers in-tree

---

CHANGELOG.md
singularity-eos/eos/eos_stellar_collapse.hpp

Not sure how this bug persisted for so long. Missing using statement in `StellarCollapse`. Caught (ironically) while debugging builds on Chicoma.

[trivial] fix callable interp

---

doc/sphinx/src/using-closures.rst

Fixes a small typo in the closure model documentation
- N/A Make sure the copyright notice on any files you modified is up to date.
- N/A After creating a pull request, note it in the CHANGELOG.md file.
- N/A LANL employees: make sure tests pass both on the github CI and on the Darwin CI
- N/A Update the version in cmake.
- N/A Move the changes in the CHANGELOG.md file under a new header for the new release, and reset the categories.

Fix typo in documentation

---

.gitlab-ci.yml
CMakeLists.txt
cmake/install.cmake
singularity-eos/CMakeLists.txt

As @dholladay00 commented in PR #348 , the `singularity_eos.{cpp,hpp}` files should only be built when fortran is on to minimize build times for C++ codes. This reverts that change. 

move the singularity_eos cpp files back into the fortran build only

---

doc/sphinx/src/using-closures.rst

Updates the PTE solver documentation. Here is a summary of the additions/changes
- N/A LANL employees: make sure tests pass both on the github CI and on the Darwin CI

Update closure model documentation

---

CHANGELOG.md
doc/sphinx/src/using-eos.rst
python/module.cpp
singularity-eos/base/constants.hpp
test/python_bindings.py

As discussed with @dholladay00 and @gopsub , this adds `lambda` to the `thermalq`s list, allowing, on a per-EOS basis, users to request `FillEos` to do something with input lambdas.

Add lambda thermalq

---

CHANGELOG.md
singularity-eos/eos/eos_spiner.hpp

Fixes a (potential) bug in Spiner EOS bulk modulus calculation.
Despite the bulk modulus being a required table in a SpinerDependsRhoT or SpinerDependsRhoSie EOS file, it is overwritten by functions `fixBulkModulus_` and `calcBMod_`, respectively.  Inside these functions, the bulk modulus formulae assume `dpdrho` to be $\partial P / \partial \rho \\; \vert_{T}$.  However, I believe (please check me) that spiner expects that the tables provided correspond to $\partial P / \partial \rho \\; \vert_{e}$.  This PR changes the bulk modulus formula to reflect this.  There is this trick that `eos_spiner` plays wherein if $\partial P / \partial e \\; \vert_{\rho} < 0$, it modifies the bulk modulus calculation.  I tried to preserve this behavior by defining $\partial P / \partial \rho \\; …

Fix bulk modulus calculation in spiner EOS

---

CHANGELOG.md
doc/sphinx/src/models.rst
doc/sphinx/src/modifiers.rst
python/module.cpp
singularity-eos/eos/eos_davis.hpp
singularity-eos/eos/singularity_eos.cpp
singularity-eos/eos/singularity_eos.f90
singularity-eos/eos/singularity_eos.hpp
test/pte_test_utils.hpp
test/python_bindings.py
test/test_f_iface.f90

We were taking the `E0` parameter in the Davis Products EOS but not actually using it anywhere.
This MR simply subtracts the `E0` from the normal reference isentrope, which I _believe_ should be sufficient and consistent in the rest of the EOS since `es` is involved in all the energy expressions.
I also added a comment basically repeating the need described in https://github.com/lanl/singularity-eos/issues/260 for an iterative procedure to find the CJ energy from a reference state.
NOTE: This is really just a quick fix so I haven't added any unit tests. I hope to add a more complete set of tests later with a bit more of a revamp to the EOS.

Remove E0 from Davis Products EOS

---

CHANGELOG.md
singularity-eos/CMakeLists.txt
singularity-eos/base/error_utils.hpp
singularity-eos/eos/get_sg_eos.cpp
singularity-eos/eos/get_sg_eos.hpp
singularity-eos/eos/get_sg_eos_functors.hpp
singularity-eos/eos/get_sg_eos_p_t.cpp
singularity-eos/eos/get_sg_eos_rho_e.cpp
singularity-eos/eos/get_sg_eos_rho_p.cpp
singularity-eos/eos/get_sg_eos_rho_t.cpp
singularity-eos/eos/singularity_eos.f90
singularity-eos/eos/singularity_eos.hpp
utils/scripts/format.sh

When the library is built with debug flags, this adds introspection functions to the `init` and `final` functors in the `get_sg_eos` interface.
These functions check to make sure the values being passed are either zero or normal. I'm using slightly more complicated logic than just `is_finite` so that I can detect underflow values as well. For some quantities, I'm also including checks to make sure the returned value is strictly positive or non-negative where appropriate.
- N/A Update the version in cmake.
- N/A Move the changes in the CHANGELOG.md file under a new header for the …

Add introspection to `get_sg_eos` interface

---

singularity-eos/eos/get_sg_eos_functors.hpp

Currently building in release mode on main gives the following errors:
```console
78     In file included from /var/folders/c7/8jd35_cn1d780xhx4jwpzt40000rgj/T/ptb/spack-stage/spack-stage-singularity-eos-git.8260182
f89897aefdf2e34fd30a11e7f7777eec9_1.8.2-ukalvuw2x2ig5e46ryqqozonojzwhwtu/spack-src/singularity-eos/eos/get_sg_eos_rho_t.cpp:19
:
>> 79     /var/folders/c7/8jd35_cn1d780xhx4jwpzt40000rgj/T/ptb/spack-stage/spack-stage-singularity-eos-git.8260182f89897aefdf2e34fd30a11
e7f7777eec9_1.8.2-ukalvuw2x2ig5e46ryqqozonojzwhwtu/spack-src/singularity-eos/eos/get_sg_eos_functors.hpp:383:2: error: expecte
d ';' after struct
80     } // namespace singularity
81      ^
82      ;
>> 83     /var/folders/c7/8jd35_cn1d780xhx4jwpzt40000rgj/T/ptb/spack-stage/spack-stage-singularity-eos-git.8260182f898 …
```

Fix #endif locations

---

singularity-eos/CMakeLists.txt

Add `eos/eos_powermg.hpp` to installed headers

Add missing eos_powermg header to install

---

spack-repo/packages/singularity-eos/package.py

This simplifies the plugin spack situation by just treating plugins like any other code dependencies.
Each plugin just has to install its source code into the spack prefix and the singularity-eos plugin needs to be registered using its name, spack package name, and the relative path to the plugins source code.

treat plugins as code dependencies

---

CHANGELOG.md
CMakeLists.txt

Prepare for release! 
@Yurlungur @jhp-lanl @rbberger @mauneyc-LANL 

update cmakelists for release.

---

CHANGELOG.md
singularity-eos/closure/mixed_cell_models.hpp
test/test_closure_pte.cpp

The _total_ volumetric internal energy 
$$ u_\mathrm{total} = \sum_m \bar{\rho}_m e_m $$  
can be a negative quantity.  I believe that the internal energy scaling routines in `singularity/main` `mixed_cell_models.hpp` do not respect this.  For example, here: https://github.com/lanl/singularity-eos/blob/main/singularity-eos/closure/mixed_cell_models.hpp#L313, an `abs` is applied to the (potentially negative) `sie_total` to compute `uscale`.  In the case of a negative `sie_total`, the sum of the resultant, scaled `u[m]` can be `-1`.  Inside residual calculations (e.g., https://github.com/lanl/singularity-eos/blob/main/singularity-eos/closure/mixed_cell_models.hpp#L594), a positive 1 is assumed for the sum over scaled material internal energies.  
I believe the fix here is to just remove the …

Fix for internal energy scaling in PTE closure

---

CHANGELOG.md
python/module.cpp
singularity-eos/eos/eos_variant.hpp
test/python_bindings.py

Added StiffGas into module.cpp so that stiff gas can be called in python bindings. 
Can be called using (for example): 
```python
from singularity_eos import StiffGas
gm1 = 5./3. - 1
Cv = 2
gamma = 5./3.
q = -(gamma/(gamma-1))
P_inf = 1
sing_stiff_gas = StiffGas(gm1, Cv, P_inf, q)
```

Sgerberding adding python eos

---

.github/workflows/tests_minimal.yml
test/test_bounds.cpp

In PR #330 I missed an include guard in the new tests. Here the guard is added. Resolves #405 .

[trivial][bugfix] add include guard

---

CHANGELOG.md
cmake/singularity-eos/hdf5.cmake
singularity-eos/closure/kinetic_phasetransition_methods.hpp
singularity-eos/closure/kinetic_phasetransition_models.hpp
singularity-eos/closure/kinetic_phasetransition_utils.hpp
singularity-eos/eos/eos_eospac.hpp
test/CMakeLists.txt
test/test_eos_tabulated.cpp

In the previous serialization MR #410 I punted one issue with EOSPAC. This MR now fixes the inconsistencies. I test EOSPAC with shared memory in the unit tests and I update the default cmake option to assume shared memory is available.
I also had to add some link libraries (available in the standard library) that HDF5 depends on to FindHDF5 as cmake was not properly adding them. 

eospac serialization fix

---

.github/workflows/tests_minimal_kokkos.yml
CHANGELOG.md
CMakeLists.txt
test/pte_longtest_2phaseVinetSn.hpp
test/pte_test_2phaseVinetSn.hpp
test/pte_test_3mat_analytic.hpp
test/pte_test_5phaseSesameSn.hpp
test/test_get_sg_eos.cpp
test/test_pte.cpp
test/test_pte_2phase.cpp
test/test_pte_3phase.cpp

What it says on the can. In a previous MR (where I was cleaning things up) I broke the test in `test_get_sg_eos`. I'm not sure why the CI didn't catch this---going to leave that mystery to @rbberger . To reproduce, build with at least
```
﻿﻿﻿﻿﻿cmake -DSINGULARITY_USE_KOKKOS=ON -DSINGULARITY_BUILD_TESTS=ON -DSINGULARITY_USE_FORTRAN=ON -DSINGULARITY_FORCE_SUBMODULE_MODE=ON ..
```
This MR resolves the issue and also cleans up the organization of the tests a bit by:
- Renaming the offending header file something more descriptive
- Moving the variant declarations (when they are needed by tests) into the implementation files
- Making the tests not depend on include order by more properly templating the `set_eos` function
I also thread through a missing cmake definition for fast logs. Unrelated …

Cleanup test PTE structure and remove variant from shared header

---

.gitignore
.gitlab-ci.yml
.gitlab/build_and_test.cmake
.gitlab/build_and_test.sh
.gitlab/common.yml
spack-repo/packages/ports-of-call/package.py
spack-repo/packages/singularity-eos/package.py
spack-repo/packages/spiner/package.py
utils/gpu_compatibility.patch

- adds CI for ATS4
- updates patch for spark-variant to support ROCm

Changes for ATS4

---

CHANGELOG.md
cmake/singularity-eos/mpark_variant.cmake

The `variant` patch erroneously referenced the old `cuda_compatibility.patch`. This PR fixes that to point to `gpu_compatibility.patch`.

Fix reference to old cuda_compatibility patch

---

.gitlab-ci.yml
.gitlab/common.yml
CMakeLists.txt
sesame2spiner/generate_files.cpp
singularity-eos/eos/singularity_eos.f90
test/test_closure_pte.cpp

- add ATS2 jobs
- update ATS4 to use `%cce`
- enable CDash reporting to internal LANL CDash server
- fixed a naming issue in the closure tests
Note: currently several CI jobs fail due to previous breakage.

ci: update

---

.github/workflows/sanitizer.yml
.github/workflows/warnings.yml
CHANGELOG.md
CMakeLists.txt
doc/sphinx/src/building.rst
singularity-eos/CMakeLists.txt
singularity-eos/base/root-finding-1d/root_finding.hpp
singularity-eos/closure/mixed_cell_models.hpp
singularity-eos/eos/eos_base.hpp
singularity-eos/eos/eos_gruneisen.hpp
singularity-eos/eos/eos_mgusup.hpp
singularity-eos/eos/eos_powermg.hpp
singularity-eos/eos/eos_sap_polynomial.hpp
singularity-eos/eos/eos_vinet.hpp
singularity-eos/eos/get_sg_eos_p_t.cpp
singularity-eos/eos/get_sg_eos_rho_e.cpp
singularity-eos/eos/get_sg_eos_rho_p.cpp
singularity-eos/eos/get_sg_eos_rho_t.cpp
singularity-eos/eos/modifiers/eos_unitsystem.hpp
test/CMakeLists.txt
test/test_closure_pte.cpp
test/test_eos_ideal.cpp
test/test_eos_modifiers.cpp

I ran singularity-eos through the clang address and undefined behavior sanitizer on my laptop. It found a few minor things like undefined variables, but it also found the source of the HIP segfault. The issue was that the constructors for the pte solvers use forwarding references, e.g.,
```C++
template <typename EOS_t, typename Real_t, typename CReal_t, typename Lambda_t>
PORTABLE_INLINE_FUNCTION
PTESolverFixedT(const std::size_t nmat, EOS_t &&eos, const Real vfrac_tot,
const Real T_true, Real_t &&rho, Real_t &&vfrac, Real_t &&sie,
CReal_t &&temp, Real_t &&press, Lambda_t &&lambda, Real *scratch,
const MixParams &params = MixParams())
```
but the accessors in `get_sg_eos` all call the constructor by passing in accessors to 2d views, e.g., `&rho_pte(tid, 0)` which are located from the …

Run singularity-eos through clang address sanitizer... and fix the HIP segfault!

---

CHANGELOG.md
doc/sphinx/src/models.rst
doc/sphinx/src/using-eos.rst
singularity-eos/eos/eos_base.hpp
singularity-eos/eos/eos_carnahan_starling.hpp
singularity-eos/eos/eos_davis.hpp
singularity-eos/eos/eos_eospac.hpp
singularity-eos/eos/eos_gruneisen.hpp
singularity-eos/eos/eos_helmholtz.hpp
singularity-eos/eos/eos_ideal.hpp
singularity-eos/eos/eos_jwl.hpp
singularity-eos/eos/eos_mgusup.hpp
singularity-eos/eos/eos_noble_abel.hpp
singularity-eos/eos/eos_powermg.hpp
singularity-eos/eos/eos_sap_polynomial.hpp
singularity-eos/eos/eos_spiner.hpp
singularity-eos/eos/eos_stellar_collapse.hpp
singularity-eos/eos/eos_stiff.hpp
singularity-eos/eos/eos_variant.hpp
singularity-eos/eos/eos_vinet.hpp
singularity-eos/eos/modifiers/eos_unitsystem.hpp
singularity-eos/eos/modifiers/ramps_eos.hpp
singularity-eos/eos/modifiers/relativistic_eos.hpp
singularity-eos/eos/modifiers/scaled_eos.hpp
singularity-eos/eos/modifiers/shifted_eos.hpp
test/test_eos_ideal.cpp
test/test_eos_tabulated.cpp

This MR adds mean atomic mass and number to the singularity-eos API, as required for 3T physics. To be clear these are *not* the ionization state. Rather they are fundamental properties of the atomic nuclei that make up a material. They are not integers, as they are the average over the molecular configuration. This also means they may change under chemical or nuclear burning, either by changing the nuclei themselves or by changing the chemical composition such that the average nucleus changes.
This is required for 3T because ionization models that compute an ionization state, and pieces of approximate models such as z splitting require them. However, the ionization state is a separate quantity that will be treated elsewhere, possibly in a later MR.
Tabulated EOS's will likely retrieve …

Add mean atomic mass and number

---

.gitlab/common.yml

updates some settings for venado and RZ systems

ci: update settings

---

.gitlab-ci.yml
.gitlab/build_and_test.sh
CHANGELOG.md
doc/sphinx/src/using-closures.rst
singularity-eos/closure/mixed_cell_models.hpp
test/CMakeLists.txt
test/test_closure_pte.cpp
test/test_pte.cpp
test/test_pte_ideal.cpp

This is a "working" version of the PT-space PTE solver that @dholladay00 started in MR #422, and this MR should replace that one. This version compiles and runs, although I haven't carefully checked for correctness yet. (It reports it converged at least!)
Important notes:
- This depends on MR #449 , where I make `DensityEnergyFromPressureTemperature` more robust across our EOS models and also add introspection necessary to bound the line search used in the PTE solver.
- The formulation that @jhp-lanl and @dholladay00 were working on, I believe, used analytic relations to compute derivatives with respect to pressure and temperature. We should potentially pursue this, but as a first pass, I just used finite differences with `DensityEnergyFromPressureTemperature` to build the Jacobian. …

pt space pte solver

---

cmake/install.cmake

The existing install location is not added to the `CMAKE_MODULE_PATH`. Installing into `lib/cmake/singularity-eos` fixes this issue, as that location is already in the search path.

Fixed EOSPAC.cmake Install Directory

---

CHANGELOG.md
doc/sphinx/src/models.rst
sesame2spiner/examples/unit_tests/steel.dat
sesame2spiner/generate_files.cpp
sesame2spiner/generate_files.hpp
sesame2spiner/io_eospac.cpp
sesame2spiner/io_eospac.hpp
singularity-eos/base/constants.hpp
singularity-eos/base/sp5/singularity_eos_sp5.hpp
singularity-eos/eos/eos_eospac.hpp
singularity-eos/eos/eos_spiner.hpp
test/profile_eospac.cpp
test/test_eos_tabulated.cpp

This MR is in support of partial ionization and is a follow up to #444 . Here we provide the ability to request tabulated electron and ion equations of state from the sesame database either through SpinerEOS or EOSPAC backends. To do so, I add a new enum
```C++
enum class TableSplit {Total, ElectronOnly, IonCold };
```
which can be passed into the tabulated EOS constructors. `Total` is the previous behavior and is the default. `ElectronOnly` is the electron EOS and `IonCold` is the ion. As before, EOS calls are in terms of ion mass density and either electron or ion temperature. Unlike Zpslit, the ionization fraction is implicit in the model. A given electron temperature automatically implies some ionization fraction. It doesn't need to be passed in.
To enable the electron or ion tables …

Enable electron/ion subtables for SpinerEOS and EOSPAC backends

---

CHANGELOG.md
eospac-wrapper/eospac_wrapper.cpp
singularity-eos/eos/eos_davis.hpp
singularity-eos/eos/eos_gruneisen.hpp

Recently when I added some additional safety features to EOSPAC and sesame2spiner, I added a memory error. It appears it caused a segfault for @rbberger (and I'm not sure why it didn't cause issues until now). This MR resolves the memory issue.

memory error in eospac wrapper

---

.github/workflows/tests_clang.yml
CHANGELOG.md
test/test_kpt_models.cpp

When adding clang builds to the re-git CI, @rbberger noticed that some tests were failing in the KPT test suite. This appears to be because the test cases were not properly nested. I have resolved that issue.
I am not sure why clang catches this issue but gnu does not. Indeed, neither code calls it undefined behavior, although I think it is by the documentation of the catch2 library. To help us catch similar issues in the future, I also add a more extensive "pure clang" build to the github CI build matrix.
@rbberger you're probably the only one who needs to review. @aematts and @jhp-lanl pinging you so you're aware. 

fix kpt test and add a more extensive clang github-ci test suite

---

CHANGELOG.md
doc/sphinx/src/models.rst
doc/sphinx/src/modifiers.rst
singularity-eos/base/indexable_types.hpp
singularity-eos/eos/eos_spiner.hpp

@dholladay00 note that the `mutable` members in the `Spiner` equations of state might still cause problems. I don't know if this is happening, but it's about time we remove the undefined behavior.
The recent PR #470 that introduced indexable types suggests another way to retain diagnostic capability without relying on unsafe paradigms. I optionally add indexable types for the two diagnostic variables which were mutable. They can now optionally be written to the lambda if the lambda is overloaded for them. Unlike other variables, which have backwards compatibility with integer-based indexing, these diagnostics are *only* available if the lambda supports the indexable type for them. This reflects that this isn't really intended to be a public facing API--it's a diagnostic tool used for …

Remove mutable from spiner-eos and fillin docs a bit

---

CHANGELOG.md
singularity-eos/eos/singularity_eos.f90

Initializing EOSPAC via the Fortran interface was causing a segfault because the code was writing `0.d0` to the optional argument `eospac_opts_values`. This should now be resolved.

Fix eospac_opts_values bug in Fortran interface

---

CHANGELOG.md
singularity-eos/eos/eos_base.hpp
singularity-eos/eos/eos_carnahan_starling.hpp
singularity-eos/eos/eos_davis.hpp
singularity-eos/eos/eos_electrons.hpp
singularity-eos/eos/eos_gruneisen.hpp
singularity-eos/eos/eos_helmholtz.hpp
singularity-eos/eos/eos_ideal.hpp
singularity-eos/eos/eos_jwl.hpp
singularity-eos/eos/eos_mgusup.hpp
singularity-eos/eos/eos_noble_abel.hpp
singularity-eos/eos/eos_powermg.hpp
singularity-eos/eos/eos_sap_polynomial.hpp
singularity-eos/eos/eos_spiner.hpp
singularity-eos/eos/eos_stellar_collapse.hpp
singularity-eos/eos/eos_stiff.hpp
singularity-eos/eos/eos_variant.hpp
singularity-eos/eos/eos_vinet.hpp

Moves the `scratch_size()` and `max_scratch_size()` from the EOS to the base class.
For almost all EOS, these are zero, and we don't need to keep duplicating this as we add EOS. It makes more sense to just add special versions for specific use cases.
I also made the inputs const for possible performance benefits

Move scratch_size and max_scratch_size into base class

---

CHANGELOG.md
python/module.hpp
singularity-eos/eos/eos_base.hpp
singularity-eos/eos/eos_carnahan_starling.hpp
singularity-eos/eos/eos_davis.hpp
singularity-eos/eos/eos_electrons.hpp
singularity-eos/eos/eos_eospac.hpp
singularity-eos/eos/eos_gruneisen.hpp
singularity-eos/eos/eos_helmholtz.hpp
singularity-eos/eos/eos_ideal.hpp
singularity-eos/eos/eos_jwl.hpp
singularity-eos/eos/eos_mgusup.hpp
singularity-eos/eos/eos_noble_abel.hpp
singularity-eos/eos/eos_powermg.hpp
singularity-eos/eos/eos_sap_polynomial.hpp
singularity-eos/eos/eos_spiner.hpp
singularity-eos/eos/eos_stellar_collapse.hpp
singularity-eos/eos/eos_stiff.hpp
singularity-eos/eos/eos_variant.hpp
singularity-eos/eos/eos_vinet.hpp
singularity-eos/eos/modifiers/eos_unitsystem.hpp
singularity-eos/eos/modifiers/floored_energy.hpp
singularity-eos/eos/modifiers/ramps_eos.hpp
singularity-eos/eos/modifiers/relativistic_eos.hpp
singularity-eos/eos/modifiers/scaled_eos.hpp
singularity-eos/eos/modifiers/shifted_eos.hpp
singularity-eos/eos/modifiers/zsplit_eos.hpp

Move nlambda default behavior into base class

---

CHANGELOG.md
spack-repo/packages/singularity-eos/package.py

I ran the following commands to install `singularity-eos` on macOS and Linux, but encountered an error:
```bash
cd
git clone https://github.com/spack/spack.git
source ~/spack/share/spack/setup-env.sh
spack compiler find
spack external find --not-buildable
git clone --recursive git@github.com:lanl/singularity-eos.git
spack repo add singularity-eos/spack-repo
spack install singularity-eos
==> Error: cannot load package 'singularity-eos' from the 'singularity_eos' repository: name 'spack' is not defined
```
After researching online a bit, the problem seems to boil down to this offending line in `spack-repo/packages/singularity-eos/package.py`:
```py
if spack.version.Version(spack.spack_version) >= spack.version.Version("0.17"):
```
Note that the `spack` module is not imported in the script. …

Updated package.py for singularity-eos to avoid spack.* constructs

---

CHANGELOG.md
CMakeLists.txt
doc/sphinx/src/building.rst

For whatever reason, the `stellarcollapse2spiner` option in `CMakeLists.txt` was missing. It must have been dropped during a rewrite. This re-enables it.

[trivial] fix stellarcollapse2spiner in cmake

---

CHANGELOG.md
spack-repo/packages/singularity-eos/package.py

As suggested by @thenders10 and @jhp-lanl in support of SAP.

Move the binutils dependency into the cmake debug build

---

CHANGELOG.md
singularity-eos/eos/singularity_eos.cpp
singularity-eos/eos/singularity_eos.f90
singularity-eos/eos/singularity_eos.hpp

Add TableSplit parameter to Spiner and EOSPAC EOS initializers to Fortran interface
This pull request introduces a `TableSplit` parameter to the initialization functions for Spiner EOS (both `SpinerEOSDependsRhoT` and `SpinerEOSDependsRhoSie`) and EOSPAC EOS models in the Fortran interface.
The `TableSplit` parameter has been integrated into:
- C++ functions:
- `init_sg_SpinerDependsRhoT`
- `init_sg_SpinerDependsRhoSie`
- `init_sg_eospac`
- Corresponding Fortran interface functions:
- `init_sg_SpinerDependsRhoT_f`
- `init_sg_SpinerDependsRhoSie_f`
- `init_sg_eospac_f`
For backward compatibility, overloaded versions of the C++ functions have been added that default to `TableSplit::Total` when the `split` parameter is not provided. Similarly, the Fortran interface functions now treat the …

Add TableSplit parameter to Fortran interface

---

CHANGELOG.md
singularity-eos/base/fast-math/logs.hpp

A downstream user pointed out that `TRUE` is sometimes defined as a preprocessor macro by (leaky) libraries. This eliminates potential overlap with that macro in our enum.

rename LogType::TRUE to LogType::DOUBLE

---

CHANGELOG.md
singularity-eos/eos/eos_base.hpp

@Yannicked reported in issue #508 that the copies int he base class were impacting the vector API performance. One copy is necessary (on GPUs) as the EOS object, rather than the pointer, must be captured by value. This requires either pulling out the object or capturing `*this` with, e.g., `KOKKOS_CLASS_LAMBDA`. 
However, we are currently performing two copies: 1 when we perform `CRTP` to typecast the object to the child type, and one when we capture. It turns out the first copy can be eliminated. We can simply create the CRTP by reference, as `[=]` in the lambda [implies assignment operator](https://en.cppreference.com/w/cpp/language/lambda) and so the underlying object is captured by value even if it is a reference in scope. See [here](https://godbolt.org/z/71Ghb9PWT) for an example. …

switch to const ref for CRTP then allow lambda to copy capture

---

CHANGELOG.md
singularity-eos/eos/eos_spiner_common.hpp
singularity-eos/eos/eos_spiner_rho_sie.hpp
singularity-eos/eos/eos_spiner_rho_temp.hpp

This MR continues #519 / #517 and moves toLog and fromLog into `spiner_eos_common.hpp`. I'm not sure what the problem you encountered was, @jbasabe but in cases like this, I find the best thing to do is start from a known point and incrementally make changes. This MR is the result. If this resolves your issue, I suggest we merge it into main and then into your branch.

move to_log and from_log, wrap in singularity namespace

---

CHANGELOG.md
singularity-eos/eos/eos_spiner_common.hpp
singularity-eos/eos/eos_spiner_rho_sie.hpp
singularity-eos/eos/eos_spiner_rho_temp.hpp
singularity-eos/eos/eos_stellar_collapse.hpp

#519 #521 added the cold curve to SpinerEOSDependsRhoSie. In the process, the HDF5 reading got a bit messed up. This MR resolves the issue.

bugfix for HDF5 

---

spack-repo/packages/spiner/package.py

Same as https://github.com/lanl/spiner/pull/130

spiner spack: c dependency gets pulled in through other libs

---

CHANGELOG.md
sesame2spiner/examples/unit_tests/foam.dat
singularity-eos/closure/mixed_cell_models.hpp
test/test_closure_pte.cpp

While debugging riot, I discovered another failure mode for the PTE solvers. In particular, the code has routines to enforce that volume fractions are initialized such that no materials start in a state such that dP/drho < 0. This can happen if you are to the expansion side of the minimum pressure in tension. If you start in this state, a Newton solver can't get you out of it---minimum pressure is a local extremum. 
This routine `SetVfracFromT` *does* set volume fractions to be outside of the spinodal region/vapor dome (where this can happen), but then it re-normalizes them so they sum to 1 (or vfrac_sum if specified != 1), and this can put you back into a bad state.
The proper thing to do is to use a [water filling algorithm](https://en.wikipedia.org/wiki/Water-filling_algorithm) that …

Another robustness fix for the PTE solvers

---

CHANGELOG.md
doc/sphinx/src/using-closures.rst
example/pte_2mat.cpp
singularity-eos/closure/mixed_cell_models.hpp
test/test_closure_pte.cpp
test/test_pte.cpp
test/test_pte_ideal.cpp

My previous MR #545 implemented the reduced rho-T system. However, I noticed a robustness issue which is that excluding the material with the largest mass fraction can be led astray when, for example, a heavy material is in a mixed cell with a light one. To improve robustness, the solver now switches which material to exclude every cycle. I add additional tests to add confidence for this, including a mixed Helium/Copper cell.
I also spent a lot of time thinking about what on earth the residual tolerance in the solver means and is doing. My take is the following: it is checking whether or not we consider the solver to be "good enough" after it starts to fail to find a gradient descent direction. This is indeed a common fail-safe/fallback in solvers, including in, e.g., numerical recipes. …

Robustness improvements to the reduced rho-T system and clarity in residual tol

---

CHANGELOG.md
doc/sphinx/src/using-eos.rst
singularity-eos/base/indexable_types.hpp
singularity-eos/base/variadic_utils.hpp
singularity-eos/eos/eos_electrons.hpp
singularity-eos/eos/eos_helmholtz.hpp
singularity-eos/eos/eos_spiner_rho_sie.hpp
singularity-eos/eos/eos_spiner_rho_temp.hpp
singularity-eos/eos/eos_stellar_collapse.hpp
singularity-eos/eos/modifiers/zsplit_eos.hpp
test/test_indexable_types.cpp
test/test_pte_ideal.cpp
test/test_spiner_transform.cpp

This PR creates new helper functions for indexable types that are safer to use with indexable types.
The underlying issue is that the original `Get()` helper function would try to use a type from the `IndexableTypes` namespace to get a lamda value and then it would fall back on a numerical index if that type wasn't present. The issue here is that when a types-based indexer is used, it could contain other types and we don't want to get or overwrite the value at another index.
The `safeGet()` and `safeSet()` helpers will _only_ use a numerical index if the indexer doesn't have a data member, `is_type_indexable` that is `true`. They can also detect whether or not they are passed a null pointer and appropriately do nothing.
There are also overloads for the `safe` functions that can avoid …

Create `safeGet` and `safeSet` for indexable types

---

singularity-eos/eos/eos_spiner_rho_sie.hpp
singularity-eos/eos/eos_spiner_rho_temp.hpp

@jonahm-LANL @Yurlungur added a change to how the `SpinerEOS*` classes handle density guesses for a given pressure and temperature.
This fixed a test issue I was encountering in https://github.com/lanl/singularity-eos/pull/526 where the results were not reproducible when doing the lookup from several different places.

Change search region for spiner

---

singularity-eos/closure/mixed_cell_models.hpp
singularity-eos/eos/eos_spiner_common.hpp

Eliminates a warning on GPU builds. This function never should have been a host device function.

SetRhoPMin shouldn't be a host device function
